name: Check Markdown Links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: |
            --verbose
            --include README.md
            --include docs/
            *.md
            *.ipynb